
M = {}

local highlight = function(name, def)
  return { name = name, def = def }
end

local defaultBg = "#161821"
local black = "#0f1117"
local grey = "#1e2132"

local _colors = {
  highlight("Normal", { bg = "NONE", fg = "#c6c8d1" }),
  highlight("NormalNC", { bg = grey, fg = "#c6c8d1" }),

  highlight("ColorColumn", { bg = grey, fg = "NONE" }),
  highlight("CursorColumn", { bg = grey, fg = "NONE" }),
  highlight("CursorLine", { bg = grey, fg = "NONE" }),
  highlight("Comment", { fg = "#6b7089" }),
  highlight("Conceal", { bg = defaultBg, fg = "#6b7089" }),
  highlight("Constant", { fg = "#a093c7" }),
  highlight("Cursor", { bg = "#c6c8d1", fg = defaultBg }),
  highlight("CursorLineNr", { bg = "#2a3158", fg = "#cdd1e6" }),
  highlight("Delimiter", { fg = "#c6c8d1" }),

  highlight("DiffAdd", { bg = "#45493e", fg = "#c0c5b9" }),
  highlight("DiffChange", { bg = "#384851", fg = "#b3c3cc" }),
  highlight("DiffDelete", { bg = "#53343b", fg = "#ceb0b6" }),
  highlight("DiffText", { bg = "#5b7881", fg = "#c6c8d1" }),

  highlight("Directory", { fg = "#89b8c2" }),
  highlight("Error", { bg = defaultBg, fg = "#e27878" }),
  highlight("ErrorMsg", { bg = defaultBg, fg = "#e27878" }),
  highlight("WarningMsg", { bg = defaultBg, fg = "#e27878" }),
  highlight("EndOfBuffer", { fg = "#242940" }),
  highlight("NonText", { fg = "#242940" }),
  highlight("Whitespace", { fg = "#242940" }),
  highlight("Folded", { bg = grey, fg = "#686f9a" }),
  highlight("FoldColumn", { bg = grey, fg = "#444b71" }),
  highlight("Function", { fg = "#84a0c6" }),
  highlight("Identifier", { fg = "#89b8c2" }),
  highlight("Ignore", { bg = "NONE", fg = "NONE" }),
  highlight("Include", { fg = "#84a0c6" }),
  highlight("IncSearch", { reverse = true, fg = "NONE" }),
  highlight("LineNr", { bg = grey, fg = "#444b71" }),
  highlight("MatchParen", { bg = "#3e445e", fg = "#ffffff" }),
  highlight("ModeMsg", { fg = "#6b7089" }),
  highlight("MoreMsg", { fg = "#b4be82" }),
  highlight("Operator", { fg = "#84a0c6" }),
  highlight("Pmenu", { bg = "#3d425b", fg = "#c6c8d1" }),
  highlight("PmenuSbar", { bg = "#3d425b", fg = "NONE" }),
  highlight("PmenuSel", { bg = "#5b6389", fg = "#eff0f4" }),
  highlight("PmenuThumb", { bg = "#c6c8d1", fg = "NONE" }),
  highlight("PreProc", { fg = "#b4be82" }),
  highlight("Question", { fg = "#b4be82" }),
  highlight("QuickFixLine", { bg = "#272c42", fg = "#c6c8d1" }),
  highlight("Search", { bg = "#e4aa80", fg = "#392313" }),
  highlight("SignColumn", { bg = grey, fg = "#444b71" }),
  highlight("Special", { fg = "#b4be82" }),
  highlight("SpecialKey", { fg = "#515e97" }),
  highlight("SpellBad", { fg = "NONE" }),
  highlight("SpellCap", { fg = "NONE" }),
  highlight("SpellLocal", { fg = "NONE" }),
  highlight("SpellRare", { fg = "NONE" }),
  highlight("Statement", { fg = "#84a0c6" }),
  highlight("StatusLine", { reverse = true, bg = "#17171b", fg = black }),
  highlight("StatusLineNC", { reverse = true, bg = "#3e445e", fg = black }),
  highlight("StorageClass", { fg = "#84a0c6" }),
  highlight("String", { fg = "#89b8c2" }),
  highlight("Structure", { fg = "#84a0c6" }),
  highlight("TabLine", { bg = black, fg = "#3e445e" }),
  highlight("TabLineFill", { reverse = true, bg = "#3e445e", fg = black }),
  highlight("TabLineSel", { bg = defaultBg, fg = "#9a9ca5" }),
  highlight("Title", { fg = "#e2a478" }),
  highlight("Todo", { bg = "#45493e", fg = "#b4be82" }),
  highlight("Type", { fg = "#84a0c6" }),
  highlight("Underlined", { underline = true, fg = "#84a0c6" }),
  highlight("VertSplit", { bg = grey, fg = grey }),
  highlight("Visual", { bg = "#272c42", fg = "NONE" }),
  highlight("VisualNOS", { bg = "#272c42", fg = "NONE" }),
  highlight("WildMenu", { bg = "#d4d5db", fg = "#17171b" }),
  highlight("diffAdded", { fg = "#b4be82" }),
  highlight("diffRemoved", { fg = "#e27878" }),
  highlight("DiagnosticUnderlineInfo", { }),
  highlight("DiagnosticInfo", { fg = "#89b8c2" }),
  highlight("DiagnosticSignInfo", { bg = grey, fg = "#89b8c2" }),
  highlight("DiagnosticUnderlineHint", { }),
  highlight("DiagnosticHint", { fg = "#6b7089" }),
  highlight("DiagnosticSignHint", { bg = grey, fg = "#6b7089" }),
  highlight("DiagnosticUnderlineWarn", {  }),
  highlight("DiagnosticWarn", { fg = "#e2a478" }),
  highlight("DiagnosticSignWarn", { bg = grey, fg = "#e2a478" }),
  highlight("DiagnosticUnderlineError", { }),
  highlight("DiagnosticError", { fg = "#e27878" }),
  highlight("DiagnosticSignError", { bg = grey, fg = "#e27878" }),
  highlight("DiagnosticFloatingHint", { bg = "#3d425b", fg = "#c6c8d1" }),

  -- Treesitter
  highlight("TSFunction", { fg = "#a3adcb" }),
  highlight("TSFunctionBuiltin", { fg = "#a3adcb" }),
  highlight("TSFunctionMacro", { fg = "#a3adcb" }),
  highlight("TSMethod", { fg = "#a3adcb" }),
  highlight("TSURI", { fg = "#89b8c2"  }),
  highlight("TSAttribute", { fg = "#b4be82" }),
  highlight("TSBoolean", { fg = "#a093c7" }),
  highlight("TSCharacter", { fg = "#a093c7" }),
  highlight("TSComment", { fg = "#6b7089" }),
  highlight("TSConstructor", { fg = "#c6c8d1" }),
  highlight("TSConditional", { fg = "#84a0c6" }),
  highlight("TSConstant", { fg = "#a093c7" }),
  highlight("TSConstBuiltin", { fg = "#a093c7" }),
  highlight("TSConstMacro", { fg = "#a093c7" }),
  highlight("TSError", { bg = defaultBg, fg = "#e27878" }),
  highlight("TSException", { fg = "#84a0c6" }),
  highlight("TSField", { fg = "#c6c8d1" }),
  highlight("TSFloat", { fg = "#a093c7" }),
  highlight("TSInclude", { fg = "#84a0c6" }),
  highlight("TSKeyword", { fg = "#84a0c6" }),
  highlight("TSKeywordFunction", { fg = "#84a0c6" }),
  highlight("TSLabel", { fg = "#b4be82" }),
  highlight("TSNamespace", { fg = "#84a0c6" }),
  highlight("TSNumber", { fg = "#a093c7" }),
  highlight("TSOperator", { fg = "#c6c8d1" }),
  highlight("TSParameter", { fg = "#c6c8d1" }),
  highlight("TSParameterReference", { fg = "#c6c8d1" }),
  highlight("TSProperty", { fg = "#c6c8d1" }),
  highlight("TSPunctDelimiter", { fg = "#c6c8d1" }),
  highlight("TSPunctBracket", { fg = "#c6c8d1" }),
  highlight("TSPunctSpecial", { fg = "#b4be82" }),
  highlight("TSRepeat", { fg = "#84a0c6" }),
  highlight("TSString", { fg = "#89b8c2" }),
  highlight("TSStringRegex", { fg = "#89b8c2" }),
  highlight("TSStringEscape", { fg = "#b4be82" }),
  -- highlight("TSTag" htmlTagName),
  -- highlight("TSTagAttribute" htmlArg),
  -- highlight("TSTagDelimiter" htmlTagName),
  highlight("TSText", { fg = "#c6c8d1" }),
  highlight("TSTitle", { fg = "#e2a478" }),
  highlight("TSType", { fg = "#84a0c6" }),
  highlight("TSTypeBuiltin", { fg = "#84a0c6" }),
  highlight("TSVariable", { fg = "#c6c8d1" }),
  highlight("TSVariableBuiltin", { fg = "#84a0c6" }),

  -- Statusline custom highlight group
  highlight("StatusLeftFile",     { fg = "#6b7089", bg = "#2e313f" }),
  highlight("StatusBase",         { fg = "#3e445e", bg = "#0f1117" }),
  highlight("StatusLeftLspError", { fg = defaultBg, bg = "#e27878"}),
  highlight("StatusLeftLspWarn",  { fg = defaultBg, bg = "#e2a478"}),
  highlight("StatusLeftLspInfo",  { fg = defaultBg, bg = "#89b8c2"}),
  highlight("StatusLeftLspHint",  { fg = defaultBg, bg = "#6b7089"}),
  highlight("StatusLeftLspOk",    { fg = defaultBg, bg = "#b4be82"}),
}

function M.colors()
  for _, hi in ipairs(_colors) do
    vim.api.nvim_set_hl(0, hi.name, hi.def)
  end
end

return M
